# What is TensorFlow?
    TensorFlow is the worlds most used library for Machine Learning and Deep learning used for create a . Developed in 2015 by the Google Brain Team, it ensures to provide an easy-to-use low-level toolkit that can handle complex mathematical operations and learning architectures.

# What are tensors?
    Tensors are similar to arrays in programming languages, but here, they are of higher dimensions. It can be considered as a generalization of matrices that form an n-dimensional array. TensorFlow provides methods that can be used to create tensor functions and compute their derivatives easily. This is what sets tensors apart from the NumPy arrays.

In [1]:
# import torch

# print("Number of GPU: ", torch.cuda.device_count())
# print("GPU Name: ", torch.cuda.get_device_name())


# device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
# print('Using device:', device)
import tensorflow as tf
print(tf.config.list_physical_devices('GPU'))

[]


### **What is a Tensor?**  
A **tensor** is a mathematical object that generalizes scalars, vectors, and matrices to higher dimensions. Tensors represent data in multi-dimensional arrays and are used extensively in machine learning frameworks such as TensorFlow and PyTorch.  

- **Scalar**: A single number (0D tensor)  
- **Vector**: A 1D array of numbers (1D tensor)  
- **Matrix**: A 2D grid of numbers (2D tensor)  
- **Higher-order tensor**: Tensors can extend to 3D and beyond, like a collection of matrices or higher-dimensional data structures.

For example:
- A **3D tensor** could represent a batch of color images, with dimensions `[batch_size, height, width, channels]`.  

---

### **Difference between Tensor and Array**  

| **Aspect**          | **Tensor**                                      | **Array**                                     |
|---------------------|--------------------------------------------------|-----------------------------------------------|
| **Definition**      | Multi-dimensional data structure (generalized).  | N-dimensional grid of values.                |
| **Framework**       | Used in machine learning libraries like TensorFlow or PyTorch. | Used in general programming, such as NumPy arrays in Python. |
| **Operations**      | Supports automatic differentiation (backpropagation). | Requires manual differentiation (if needed).|
| **Purpose**         | Specifically designed for deep learning and differentiable operations. | Used for general data storage and computations. |
| **Backend Optimization** | Optimized for GPU and distributed systems in deep learning frameworks. | Not inherently optimized for GPU operations. |
| **Example Usage**   | TensorFlow, PyTorch for neural networks.         | NumPy for scientific computing.              |

---

### **Summary**  
- A **tensor** is conceptually similar to an **array** but optimized for operations used in deep learning and differentiable computations.
- While arrays (like in NumPy) are used for general mathematical operations, **tensors** are primarily used in deep learning frameworks, where they offer additional functionalities, such as gradient tracking for optimization.

Sure! Here’s a very simple explanation with day-to-day examples:

---

### **1. Scalar (0D Tensor)**  
- **Definition**: A single number.  
- **Example**:  
  - Temperature today: **30°C**  
  - Weight of an apple: **150 grams**  

This is just one value—no direction, no dimensions.

---

### **2. Vector (1D Tensor)**  
- **Definition**: A list of numbers arranged in one row or one column (1D).  
- **Example**:  
  - Shopping quantities:  
    \[ [2, 4, 1] \]  
    Meaning: 2 apples, 4 bananas, 1 orange.

Each number represents a quantity of an item.

---

### **3. Matrix (2D Tensor)**  
- **Definition**: A grid of numbers (rows and columns).  
- **Example**:  
  - A table of student test scores:

    \[
    \begin{matrix}
    85 & 90 & 78 \\
    88 & 92 & 80 \\
    70 & 75 & 82
    \end{matrix}
    \]

Each row represents a student, and each column represents a subject (e.g., Math, Science, English).

---

These examples show how scalars, vectors, and matrices naturally occur in everyday situations and data.

# Basics

In [3]:
import tensorflow as tf

In [2]:
# This will be an int32 tensor by default; see "dtypes" below.
rank_0_tensor = tf.constant(4)
print(rank_0_tensor)

tf.Tensor(4, shape=(), dtype=int32)


In [10]:
# Let's make this a float tensor.
rank_1_tensor = tf.constant([2.0, 3.0, 4.0])
print(rank_1_tensor)

tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)


In [4]:
# If you want to be specific, you can set the dtype (see below) at creation time
rank_2_tensor = tf.constant([[1, 2],
                             [3, 4],
                             [5, 6]], dtype=tf.float16)
print(rank_2_tensor)

tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float16)


In [12]:
# There can be an arbitrary number of
# axes (sometimes called "dimensions")
rank_3_tensor = tf.constant([
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9]],
  [[10, 11, 12, 13, 14],
   [15, 16, 17, 18, 19]],
  [[20, 21, 22, 23, 24],
   [25, 26, 27, 28, 29]],])

print(rank_3_tensor)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


In [13]:
# why keras is inside with tensor ?
#     #

In [16]:
a = tf.constant([[1, 2],
                 [3, 4]])
b = tf.constant([[1, 1],
                 [1, 1]]) # Could have also said `tf.ones([2,2], dtype=tf.int32)`

print(tf.add(a, b), "\n")
print(tf.multiply(a, b), "\n")
print(tf.matmul(a, b), "\n")

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32) 



In [20]:
# https://www.tensorflow.org/guide/tensor

In [22]:
# Indexing
rank_1_tensor = tf.constant([0, 1, 1, 2, 3, 5, 8, 13, 21, 34])
print(rank_1_tensor.numpy())

[ 0  1  1  2  3  5  8 13 21 34]


In [23]:
print("First:", rank_1_tensor[0].numpy())
print("Second:", rank_1_tensor[1].numpy())
print("Last:", rank_1_tensor[-1].numpy())

First: 0
Second: 1
Last: 34


In [24]:
print("Everything:", rank_1_tensor[:].numpy())
print("Before 4:", rank_1_tensor[:4].numpy())
print("From 4 to the end:", rank_1_tensor[4:].numpy())
print("From 2, before 7:", rank_1_tensor[2:7].numpy())
print("Every other item:", rank_1_tensor[::2].numpy())
print("Reversed:", rank_1_tensor[::-1].numpy())

Everything: [ 0  1  1  2  3  5  8 13 21 34]
Before 4: [0 1 1 2]
From 4 to the end: [ 3  5  8 13 21 34]
From 2, before 7: [1 2 3 5 8]
Every other item: [ 0  1  3  8 21]
Reversed: [34 21 13  8  5  3  2  1  1  0]


In [25]:
print(rank_2_tensor.numpy())

[[1. 2.]
 [3. 4.]
 [5. 6.]]


In [5]:
# Get row and column tensors
print("Second row:", rank_2_tensor[1, :].numpy())
print("Second column:", rank_2_tensor[:, 1].numpy())
print("Last row:", rank_2_tensor[-1, :].numpy())
print("First item in last column:", rank_2_tensor[0, -1].numpy())
print("Skip the first row:")
print(rank_2_tensor[1:, :].numpy(), "\n")


Second row: [3. 4.]
Second column: [2. 4. 6.]
Last row: [5. 6.]
First item in last column: 2.0
Skip the first row:
[[3. 4.]
 [5. 6.]] 



In [50]:
rank_2_tensor

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)>

In [6]:
tf.reshape(rank_2_tensor,[2,3])

<tf.Tensor: shape=(2, 3), dtype=float16, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float16)>

In TensorFlow, a **tensor** is a multi-dimensional array of data. Tensors are the fundamental units of data in TensorFlow, and there are several types, categorized by their **dimensionality**, **usage**, and **content**. Below is a breakdown of the main types of tensors and their characteristics.

---

## 1. **Based on Rank (Dimensionality)**  
The rank of a tensor refers to the number of dimensions (axes) it has.

### **0D Tensor (Scalar)**  
- A tensor with **no dimensions**; it holds a single value.  
- Example:
  ```python
  scalar = tf.constant(5)
  print(scalar)  # <tf.Tensor: shape=(), dtype=int32, numpy=5>
  ```

### **1D Tensor (Vector)**  
- A **single-dimensional array** that contains multiple values.
- Example:
  ```python
  vector = tf.constant([1, 2, 3])
  print(vector)  # <tf.Tensor: shape=(3,), dtype=int32>
  ```

### **2D Tensor (Matrix)**  
- A tensor with **two dimensions** (rows and columns).
- Example:
  ```python
  matrix = tf.constant([[1, 2], [3, 4]])
  print(matrix)  # <tf.Tensor: shape=(2, 2), dtype=int32>
  ```

### **3D Tensor**  
- A tensor with **three dimensions**, often used to represent sequences of matrices (like an image stack or batch of sequences).
- Example:
  ```python
  tensor_3d = tf.zeros([3, 2, 2])
  print(tensor_3d)  # Shape: (3, 2, 2)
  ```

### **n-D Tensor**  
- Tensors with **n dimensions** (where n > 3) can represent more complex data, such as batches of images with multiple channels.
- Example:
  ```python
  tensor_4d = tf.ones([10, 64, 64, 3])  # A batch of 10 RGB images (64x64)
  print(tensor_4d.shape)  # (10, 64, 64, 3)
  ```

---

## 2. **Based on Data Type**
Tensors can store data of different types, such as:
- **Integer**: `tf.int32`, `tf.int64`
- **Floating point**: `tf.float32`, `tf.float64`
- **Boolean**: `tf.bool`
- **String**: `tf.string`

Example:
```python
float_tensor = tf.constant([1.0, 2.5, 3.3], dtype=tf.float32)
print(float_tensor)  # <tf.Tensor: shape=(3,), dtype=float32>
```

---

## 3. **Based on Mutability**  
TensorFlow defines tensors with different mutability characteristics:

### **Constant Tensor**
- Immutable tensors that cannot change their values after creation.
- Created using `tf.constant()`.

```python
const_tensor = tf.constant([1, 2, 3])
```

### **Variable Tensor**
- Mutable tensors that can change values during model training or execution.
- Created using `tf.Variable()`.

```python
var_tensor = tf.Variable([1, 2, 3])
var_tensor.assign([4, 5, 6])  # Modify the tensor
```

---

## 4. **Based on Content (Special Tensors)**  
TensorFlow offers several predefined tensors with specific patterns or initializations.

### **Zeros Tensor**
- A tensor filled with zeros.
```python
zeros = tf.zeros([2, 3])
```

### **Ones Tensor**
- A tensor filled with ones.
```python
ones = tf.ones([3, 3])
```

### **Identity Tensor**
- A tensor representing an identity matrix.
```python
identity = tf.eye(4)  # 4x4 identity matrix
```

### **Random Tensor**
- A tensor filled with random values (uniform or normal distribution).
```python
random_uniform = tf.random.uniform([2, 2], minval=0, maxval=1)
random_normal = tf.random.normal([2, 2], mean=0, stddev=1)
```

---

## 5. **Sparse Tensor**
Sparse tensors are used to efficiently represent data with a lot of zeros.

```python
sparse_tensor = tf.sparse.SparseTensor(
    indices=[[0, 0], [1, 2]],
    values=[1, 2],
    dense_shape=[3, 4]
)
print(sparse_tensor)
```

---

## 6. **Ragged Tensor**
Ragged tensors allow for **variable-length dimensions**, which is useful when working with data like sentences of different lengths.

```python
ragged_tensor = tf.ragged.constant([[1, 2, 3], [4, 5], [6]])
print(ragged_tensor)
```

---

## 7. **TensorArray**
- A TensorArray is a **dynamically sized array of tensors**, useful for constructing sequences with unknown lengths during model execution (e.g., RNNs).

```python
ta = tf.TensorArray(dtype=tf.float32, size=0, dynamic_size=True)
ta = ta.write(0, [1.0, 2.0])
print(ta.read(0))
```

---

### Summary Table of Tensor Types

| **Tensor Type**   | **Description**                                  | **Example Usage**                 |
|-------------------|---------------------------------------------------|-----------------------------------|
| Scalar (0D)       | Single value                                      | Loss value, learning rate        |
| Vector (1D)       | One-dimensional array                             | Weight vector                    |
| Matrix (2D)       | Two-dimensional grid                              | Image (grayscale)                |
| 3D/4D Tensor      | Multi-dimensional array                           | Batch of RGB images              |
| Sparse Tensor     | Efficiently stores mostly-zero data               | Graph data, word embeddings      |
| Ragged Tensor     | Stores variable-length data efficiently           | Text sequences of varying lengths|
| TensorArray       | Dynamically sized tensor array                    | RNNs with unknown sequence length|

---

Let me know if you need further clarification!

In [7]:
# Define two tensors with different shapes
a = tf.constant([[1, 2, 3], [4, 5, 6]])  # Shape (2, 3)
b = tf.constant([10, 20, 30])            # Shape (3,)

# Tensor 'b' will be broadcast to shape (2, 3)
result = a + b
print(result)


tf.Tensor(
[[11 22 33]
 [14 25 36]], shape=(2, 3), dtype=int32)
